In [1]:

#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers


   ---------------------------------------- 0.0/18.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/18.8 MB ? eta -:--:--
   - -------------------------------------- 0.8/18.8 MB 3.1 MB/s eta 0:00:06
   - -------------------------------------- 0.8/18.8 MB 3.1 MB/s eta 0:00:06
   -- ------------------------------------- 1.0/18.8 MB 2.0 MB/s eta 0:00:10
   -- ------------------------------------- 1.3/18.8 MB 1.7 MB/s eta 0:00:11
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/18.8 MB 1.5 MB/s eta 0:00:12
   --- ------

In [3]:

%pip install pandas

# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 7.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.0 MB 6.3 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.0 MB 5.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.0 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.0 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/11.0 MB 3.5 MB/s eta 0:00:03
   -------------- ------------------------- 3.9/11.0 MB 2.9 MB/s eta 0:00:03
   --------------- ------------------------ 4.2/11.0 MB 2.7 MB/s eta 0:00:03
   ---------------- ----------------------- 4.5/11.0 MB 2.7 MB/s eta 0:00:03
   ----------------- ---------------------- 4.7/11.0 MB 2.4 MB/s eta 0:00:03
   ------------------ --------------------- 5.0/11.0 MB 2.4 MB/s eta 0:00:03
   ---------------

In [ ]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

  Using cached transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
  Using cached torch-2.9.1-cp313-cp313-win_amd64.whl.metadata (30 kB)
  Using cached scipy-1.16.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
   ---------------------------------------- 0.0/12.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.0 MB ? eta -:--:--
    --------------------------------------- 0.3/12.0 MB ? eta -:--:--
    --------------------------------------- 0.3/12.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.0 MB 539.0 kB/s eta 0:00:22
   - -------------------

In [5]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

### Step 1 : Create source embeddings for the text column

In [ ]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")
# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(df.text)
embeddings.shape

(8, 384)

In [12]:
embeddings

array([[ 0.06386315,  0.02910283,  0.00976355, ...,  0.01023018,
        -0.02231211, -0.00268407],
       [-0.05709034,  0.09636036,  0.00199014, ...,  0.06168114,
        -0.0226081 ,  0.03472494],
       [-0.08079229, -0.03503961,  0.03106481, ..., -0.16189392,
         0.01315192,  0.05600094],
       ...,
       [-0.03807865,  0.00503377, -0.06084295, ..., -0.03014938,
        -0.05972218,  0.04858848],
       [ 0.09595466, -0.01580386,  0.00767662, ..., -0.06537455,
        -0.07525399, -0.04042165],
       [ 0.15049903, -0.01106239, -0.02882514, ..., -0.07340208,
        -0.05694251,  0.02461096]], shape=(8, 384), dtype=float32)

In [13]:
dim = embeddings.shape[1]
dim

384

### Step 2 : Build a FAISS Index for vectors

In [14]:
import faiss

index = faiss.IndexFlatL2(dim)

### Step 3 : Normalize the source vectors (as we are using L2 distance to measure similarity) and add to the index

In [ ]:
index.add(embeddings)
index

In [ ]:

search_query = "I want to buy a polo t-shirt"
# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(384,)

In [ ]:
import numpy as np
svec = np.array(vec).reshape(1, -1)
svec.shape

(1, 384)

In [19]:
index.search(svec, k=2)

(array([[1.4139273, 1.4256653]], dtype=float32), array([[3, 2]]))

In [21]:

distances, I = index.search(svec, k=2)
distances

array([[1.4139273, 1.4256653]], dtype=float32)

In [22]:
I

array([[3, 2]])

In [27]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [26]:
df.loc[I[0]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion